"""Moirai brand constants shared by the admin console and the public dashboard.

The mark is the solid (one-strand) Moirai mark, the same geometry as `brand/logo/moirai-mark-solid.svg`, and
the wordmark is `brand/logo/moirai-wordmark.svg` (both generated by `scripts/brand_logo.py`); the favicon is
`brand/export/favicon-32.png`. Inside the apps the mark is served as a CSS background (`theme.stylesheet`)
because the HTML sanitizer of `st.html` strips inline SVG; the sidebar lockup goes through `st.logo`.
This module is standard library only: the public dashboard imports it and must never load console code.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final, Literal
from urllib.parse import quote

NAME: Final[str] = "Moirai"
FAVICON: Final[str] = str(Path(__file__).parent / "console" / "static" / "moirai-favicon-32.png")

# Brand palette (`brand/brand.css`). Oxblood is the blade of the mark only, never a loss colour.
OBSIDIAN: Final[str] = "#0B0A0F"
NIGHT: Final[str] = "#16131D"
GILT: Final[str] = "#C9A55C"
BONE: Final[str] = "#ECE6D8"
ASH: Final[str] = "#8C8697"
OXBLOOD_ON_DARK: Final[str] = "#B23A34"
OXBLOOD_ON_LIGHT: Final[str] = "#8E2424"
INK: Final[str] = "#17141F"
PAPER: Final[str] = "#F4F0E6"

_MARK_STRANDS: Final[str] = (
    '<g fill="none" stroke-width="13" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="12">'
    '<polyline points="26,106 26,30 64,70 102,30 102,84" stroke="{gilt}"/>'
    '<polyline points="102,94 102,109" stroke="{blade}"/></g>'
)
_WORDMARK_STROKES: Final[str] = (
    '<g fill="none" stroke="{text}" stroke-width="4.2" stroke-linecap="butt" stroke-linejoin="miter" '
    'stroke-miterlimit="12"><polyline points="2.1,40 2.1,4.2 18,24.8 33.9,4.2 33.9,40"/>'
    '<circle cx="71" cy="20" r="17.9"/><line x1="108.1" y1="0" x2="108.1" y2="40"/>'
    '<path d="M127.3,40 V2.1 H134.4 A8.9,8.9 0 0 1 134.4,19.9 H127.3 M132.4,19.9 L152.2,40"/>'
    '<polyline points="168.2,40 186.2,2.52 204.2,40"/><line x1="221.3" y1="0" x2="221.3" y2="40"/></g>'
)
_SVG_OPEN: Final[str] = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="{box}">'


def _data_uri(svg: str) -> str:
    return "data:image/svg+xml," + quote(svg, safe="")


def lockup_svg(mode: Literal["dark", "light"]) -> str:
    """Horizontal lockup (solid mark + wordmark) for `st.logo`, cropped to the ink, Bone or Ink letters."""
    text, blade = (BONE, OXBLOOD_ON_DARK) if mode == "dark" else (INK, OXBLOOD_ON_LIGHT)
    return (
        _SVG_OPEN.format(box="16 18 346 94")
        + _MARK_STRANDS.format(gilt=GILT, blade=blade)
        + '<g transform="translate(134 45)">'
        + _WORDMARK_STROKES.format(text=text)
        + "</g></svg>"
    )


MARK_DATA_URI: Final[str] = _data_uri(
    _SVG_OPEN.format(box="0 0 128 128") + _MARK_STRANDS.format(gilt=GILT, blade=OXBLOOD_ON_DARK) + "</svg>"
)
# The three-strand mark (`brand/logo/moirai-mark.svg`), for large decorative use such as the equity hero.
STRANDS_DATA_URI: Final[str] = _data_uri(
    _SVG_OPEN.format(box="0 0 128 128")
    + f'<g fill="none" stroke="{GILT}" stroke-width="3.2" stroke-linecap="butt" stroke-linejoin="miter" '
    'stroke-miterlimit="12"><polyline points="18,106 18,9.96 64,58.38 110,9.96 110,72.46"/>'
    '<polyline points="110,81.46 110,106"/><polyline points="26,106 26,30 64,70 102,30 102,75.5"/>'
    '<polyline points="102,84.5 102,106"/><polyline points="34,106 34,50.04 64,81.62 94,50.04 94,78.54"/>'
    '<polyline points="94,87.54 94,106"/></g>'
    f'<line x1="87" y1="85.7" x2="117" y2="74.3" stroke="{OXBLOOD_ON_DARK}" stroke-width="2.4"/></svg>'
)
# Letters only, drawn in black: used as a CSS mask so the wordmark takes the theme's text colour.
WORDMARK_MASK_URI: Final[str] = _data_uri(
    _SVG_OPEN.format(box="-2 -2 227.4 46") + _WORDMARK_STROKES.format(text="black") + "</svg>"
)
