"""Vault scopes: which secrets live in which scope, who may read them and where the keys are.

Scope -> services (Design Contract section 10): `data` -> recorder, news, veto-scan; `llm` -> council,
scorer, news, veto-scan; `exec` -> execution; `ops` -> telegram-bot. Exactly one service per scope runs the
owner worker (consumer group `owner-<scope>`) that tests and activates new secret versions; the other
services only read the active version.

Key material:
- public keys: `config/vault_public_keys.yaml` (committed, generated by `scripts/gen_scope_keys.py`),
- private keys: the docker secret `HDT_SCOPE_PRIVATE_KEY_FILE` of each service, a JSON object
  `{"<scope>": "<base64 private key>"}` holding only the scopes that service reads.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Final, Literal, get_args

import yaml
from nacl.public import PrivateKey
from pydantic import BaseModel, ConfigDict, Field, PositiveInt

from hdt.core.config import CONFIG_DIR, read_env_value
from hdt.vault.redact import register_secret
from hdt.vault.sealed import SealedBlobError, b64encode, private_key_from_b64, public_key_from_b64

Scope = Literal["data", "llm", "exec", "ops"]
SCOPES: Final[tuple[Scope, ...]] = get_args(Scope)
PUBLIC_KEYS_PATH: Final[Path] = CONFIG_DIR / "vault_public_keys.yaml"
PRIVATE_KEY_ENV: Final[str] = "HDT_SCOPE_PRIVATE_KEY"  # read via HDT_SCOPE_PRIVATE_KEY_FILE

SCOPE_SERVICES: Final[dict[Scope, tuple[str, ...]]] = {
    "data": ("recorder", "news", "veto_scan"),
    "llm": ("council", "scorer", "news", "veto_scan"),
    "exec": ("execution",),
    "ops": ("telegram",),
}
SCOPE_OWNER: Final[dict[Scope, str]] = {
    "data": "recorder",
    "llm": "council",
    "exec": "execution",
    "ops": "telegram",
}


class VaultKeyError(RuntimeError):
    """Scope key material is missing or inconsistent (never includes key bytes in the message)."""


# --------------------------------------------------------------------------- secret payloads


class _SecretPayload(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, hide_input_in_errors=True)


class ApiKeySecret(_SecretPayload):
    api_key: str = Field(min_length=16, max_length=512)


class BinanceKeySecret(_SecretPayload):
    api_key: str = Field(min_length=16, max_length=512)
    api_secret: str = Field(min_length=16, max_length=512)


class TelegramSecret(_SecretPayload):
    bot_token: str = Field(min_length=20, max_length=256)
    allowed_user_ids: tuple[PositiveInt, ...] = Field(min_length=1)


@dataclass(frozen=True)
class SecretSpec:
    scope: Scope
    name: str
    label: str
    payload_model: type[_SecretPayload]
    primary_field: str

    @property
    def fields(self) -> tuple[str, ...]:
        return tuple(self.payload_model.model_fields)


SECRET_SPECS: Final[dict[tuple[str, str], SecretSpec]] = {
    (spec.scope, spec.name): spec
    for spec in (
        SecretSpec("data", "cmc_api_key", "CoinMarketCap", ApiKeySecret, "api_key"),
        SecretSpec("data", "news_feed", "Full-text news feed", ApiKeySecret, "api_key"),
        SecretSpec("llm", "openrouter_api_key", "OpenRouter", ApiKeySecret, "api_key"),
        SecretSpec("llm", "deepseek_api_key", "DeepSeek", ApiKeySecret, "api_key"),
        SecretSpec("exec", "binance_testnet", "Binance testnet", BinanceKeySecret, "api_key"),
        SecretSpec("exec", "binance_live", "Binance live", BinanceKeySecret, "api_key"),
        SecretSpec("ops", "telegram", "Telegram bot", TelegramSecret, "bot_token"),
    )
}


def secret_spec(scope: str, name: str) -> SecretSpec:
    try:
        return SECRET_SPECS[(scope, name)]
    except KeyError:
        raise KeyError(f"unknown secret {scope}/{name}") from None


# --------------------------------------------------------------------------- keys


def load_public_keys(path: Path = PUBLIC_KEYS_PATH) -> dict[Scope, str]:
    """Scope -> standard base64 X25519 public key; every scope must be present and well-formed."""
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise VaultKeyError(f"{path} is missing: run scripts/gen_scope_keys.py") from exc
    keys = (data or {}).get("public_keys") if isinstance(data, dict) else None
    if not isinstance(keys, dict):
        raise VaultKeyError(f"{path} must contain a 'public_keys' mapping")
    result: dict[Scope, str] = {}
    for scope in SCOPES:
        value = keys.get(scope)
        if not isinstance(value, str):
            raise VaultKeyError(f"{path}: public key for scope '{scope}' is missing")
        try:
            result[scope] = b64encode(bytes(public_key_from_b64(value)))
        except SealedBlobError as exc:
            raise VaultKeyError(f"{path}: public key for scope '{scope}' is malformed") from exc
    return result


def parse_private_keys(text: str) -> dict[Scope, PrivateKey]:
    """Parse the private key file content; every key string is registered for log redaction."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise VaultKeyError("scope private key file must be a JSON object {scope: base64 key}") from exc
    if not isinstance(data, dict) or not data:
        raise VaultKeyError("scope private key file must be a non-empty JSON object")
    keys: dict[Scope, PrivateKey] = {}
    for scope, value in data.items():
        if scope not in SCOPES or not isinstance(value, str):
            raise VaultKeyError(f"scope private key file: unexpected entry '{scope}'")
        register_secret(value)
        try:
            keys[scope] = private_key_from_b64(value)
        except SealedBlobError as exc:
            raise VaultKeyError(f"scope private key for '{scope}' is malformed") from exc
    return keys


def load_private_key(scope: Scope, public_keys: dict[Scope, str] | None = None) -> PrivateKey:
    """The private key of `scope` from the service's docker secret, checked against the public key."""
    content = read_env_value(PRIVATE_KEY_ENV)
    if content is None:
        raise VaultKeyError(f"{PRIVATE_KEY_ENV}_FILE is not set for this service")
    keys = parse_private_keys(content)
    if scope not in keys:
        raise VaultKeyError(f"this service holds no private key for scope '{scope}'")
    expected = (public_keys or load_public_keys())[scope]
    if b64encode(bytes(keys[scope].public_key)) != expected:
        raise VaultKeyError(f"private key for scope '{scope}' does not match the published public key")
    return keys[scope]
