"""Generate the X25519 key pair of every vault scope.

Writes:
- `config/vault_public_keys.yaml` (committed): `public_keys: {scope: base64 public key}`, served to the
  browser by config-api for sealing,
- `secrets/scope_private_key.<service>.json` (git-ignored plaintext, encrypt into the sops file and
  mount as the service's `HDT_SCOPE_PRIVATE_KEY_FILE`): `{scope: base64 private key}` holding only the
  scopes that service reads (`hdt.vault.scopes.SCOPE_SERVICES`). config-api and console get no file.

Existing keys are never overwritten unless `--rotate` is given: rotating makes every stored secret
undecryptable, so all API keys must be entered again in the console afterwards. Private keys are never
printed.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hdt.vault.scopes import PUBLIC_KEYS_PATH, SCOPE_SERVICES, SCOPES, Scope  # noqa: E402
from hdt.vault.sealed import generate_keypair  # noqa: E402

SECRETS_DIR = ROOT / "secrets"
HEADER = (
    "# Vault scope public keys (X25519, standard base64), generated by scripts/gen_scope_keys.py.\n"
    "# The browser seals each secret with its scope key; only the scope's services hold the private key.\n"
)


def private_key_path(secrets_dir: Path, service: str) -> Path:
    return secrets_dir / f"scope_private_key.{service}.json"


def services_by_scope() -> dict[str, list[Scope]]:
    services: dict[str, list[Scope]] = {}
    for scope in SCOPES:
        for service in SCOPE_SERVICES[scope]:
            services.setdefault(service, []).append(scope)
    return services


def write_private(path: Path, content: str) -> None:
    """Create or replace the file with owner-only permissions from the start."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    os.replace(tmp, path)


def generate(public_path: Path, secrets_dir: Path, *, rotate: bool) -> dict[Scope, str]:
    services = services_by_scope()
    existing = [p for p in (public_path, *(private_key_path(secrets_dir, s) for s in services)) if p.exists()]
    if existing and not rotate:
        names = ", ".join(str(p) for p in existing)
        raise SystemExit(
            f"keys already exist ({names}); pass --rotate to replace them and re-enter every secret"
        )
    pairs = {scope: generate_keypair() for scope in SCOPES}
    public = {scope: pair[0] for scope, pair in pairs.items()}
    for service, scopes in services.items():
        body = {scope: pairs[scope][1] for scope in scopes}
        write_private(private_key_path(secrets_dir, service), json.dumps(body, indent=2) + "\n")
    lines = [HEADER, "public_keys:\n", *(f"  {scope}: {public[scope]}\n" for scope in SCOPES)]
    public_path.parent.mkdir(parents=True, exist_ok=True)
    public_path.write_text("".join(lines), encoding="utf-8", newline="\n")
    return public


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--rotate", action="store_true", help="replace existing keys (every secret must be re-entered)"
    )
    parser.add_argument("--public-out", type=Path, default=PUBLIC_KEYS_PATH)
    parser.add_argument("--secrets-dir", type=Path, default=SECRETS_DIR)
    args = parser.parse_args(argv)
    public = generate(args.public_out, args.secrets_dir, rotate=args.rotate)
    print(f"wrote {args.public_out}")
    for scope in SCOPES:
        print(f"  {scope}: {public[scope]}")
    for service, scopes in sorted(services_by_scope().items()):
        print(f"wrote {private_key_path(args.secrets_dir, service)} ({', '.join(scopes)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
